using System.Collections.Generic;
using Godot;
using GodotGameAIbyExample.Scripts.Extensions;

namespace GodotGameAIbyExample.Scripts.SteeringBehaviors;

/// <summary>
/// Represents an aggregator that combines goals from child nodes implementing
/// the IPipelineTargeter interface into a single aggregated goal.
/// </summary>
[Tool]
public partial class PipelineTargeterAggregator: Node
{
    private IPipelineTargeter[] _pipelineTargeters;

    /// <summary>
    /// Loads all child nodes implementing the IPipelineTargeter interface.
    /// </summary>
    /// <remarks>
    /// Be aware that order matters. Targeters will be evaluated in the order they are
    /// in the tree. So, they will be evaluated from top to bottom.
    /// </remarks>
    private void LoadPipelineTargeters()
    {
        _pipelineTargeters = this.FindChildren<IPipelineTargeter>()?.ToArray();
    }

    public override void _Ready()
    {
        LoadPipelineTargeters();
    }

    /// <summary>
    /// Aggregates the goals generated by all child nodes implementing the
    /// IPipelineTargeter interface into a combined goal.
    /// </summary>
    /// <returns>A PipelineGoal object containing the aggregated goal values
    /// derived from the child IPipelineTargeter nodes.</returns>
    public PipelineGoal GetAggregatedGoal(SteeringBehaviorArgs args)
    {
        PipelineGoal aggregatedGoal = new();
        foreach (IPipelineTargeter pipelineTargeter in _pipelineTargeters)
        {
            PipelineGoal targeterGoal = pipelineTargeter.GetGoal(args);
            if (targeterGoal == null) continue;
            aggregatedGoal.UpdateChannels(targeterGoal);
        }
        return aggregatedGoal;
    }

    public override string[] _GetConfigurationWarnings()
    {
        LoadPipelineTargeters();
        
        List<string> warnings = new();
        
        if (_pipelineTargeters == null || _pipelineTargeters.Length == 0)
        {
            warnings.Add("This node needs any child of type " +
                         "IPipelineTargeter to work.");
        }
        
        return warnings.ToArray();
    }
}